# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Text' do

pod 'AFNetworking','~> 3.1.0'
pod 'STAlertView', '~> 1.0.0'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Text

  target 'TextTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
